### ISSUE TITLE
DefaultController::mapDescriptionField() should verify the user has access to the given object

### ISSUE THREAD

**Issue by youwe-petervanderwal** [pdchaudhary/chatgpt-pimcore#2]
Currently there is no check that the user is allowed to see this object based on it's roles and workspaces. This means any logged in admin user could request any object data.

This could probably be solved with a `if (!$object->isAllowed('view')) {` which is also done by the Pimcore Admin UI.

This vulnerability doesn't affect users who are not logged in as there is (should be) a firewall already on the `/admin` url prefix

**Comment by pdchaudhary** [comment]
Fixed
