### ISSUE TITLE
JavaScript files aren't loaded correctly through combined 'ChatgptPimcoreBundle.php::getJsPaths()' and 'ChatgptPimcoreBundle.php::getEditmodeJsPaths()'

### ISSUE THREAD

**Issue by MartijnVanDoornik** [pdchaudhary/chatgpt-pimcore#3]
The loading of the JavaScript files does not seem to go correctly. JavaScript from other bundles fails when enabling this bundle.

Removing 'ChatgptPimcoreBundle.php::getEditmodeJsPaths()' and only leaving 'ChatgptPimcoreBundle.php::getJsPaths()' resolves the issue.

**Comment by pdchaudhary** [comment]
Fixed
